stateDiagram-v2
    state 상품조회 <<choice>>
    [*] --> 상품조회 : 상품 조회
    상품조회 --> 주문실패 : 판매중지
    상품조회 --> 주문실패 : 재고없음
    상품조회 --> 주문생성 : 재고있음
    주문생성 --> 결제대기 : 결제로 이동
    state 결제 <<choice>>
    결제대기 --> 결제 : 결제
    결제 --> 주문완료 : 결제완료
    결제 --> 주문취소 : 결제 취소
    결제 --> 주문실패 : 결제 실패
    주문실패 --> [*]
    주문취소 --> [*]
    주문완료 --> [*]