stateDiagram-v2
	state 상품등록 <<choice>>
	[*] --> 상품등록 : 상품등록
	상품등록 --> [*] : 등록 실패
    상품등록 --> 재고있음 : 등록 성공
    재고있음 --> 재고없음 : 재고 소진
    재고있음 --> 판매중지 : 판매 중단
    재고없음 --> 재고있음 : 재고 보충
    재고없음 --> 판매중지 : 판매 중단
    state 재고 <<choice>>
    판매중지 --> 재고 : 판매 재기
    재고 --> 재고없음 : 재고없음
    재고 --> 재고있음 : 재고있음